server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:oyjcodes/microservicecloud-config.git #GitHub上面的git仓库名字
 

